from __future__ import annotations

from pathlib import Path
import subprocess


def count_lines(path: Path) -> int:
    data = path.read_bytes()
    if not data:
        return 0
    return data.count(b"\n") + (0 if data.endswith(b"\n") else 1)


def format_number(value: int) -> str:
    return f"{value:,}".replace(",", ".")


def render_tree(node: dict, line_counts: dict[str, int], path_parts: tuple[str, ...] = (), prefix: str = "") -> list[str]:
    lines: list[str] = []
    items = sorted(node.items(), key=lambda item: (item[1] is None, item[0].casefold()))

    for index, (name, child) in enumerate(items):
        is_last = index == len(items) - 1
        branch = "└── " if is_last else "├── "

        if isinstance(child, dict):
            lines.append(f"{prefix}{branch}{name}")
            extension = "    " if is_last else "│   "
            lines.extend(render_tree(child, line_counts, path_parts + (name,), prefix + extension))
        else:
            rel_path = "/".join(path_parts + (name,))
            lines.append(f"{prefix}{branch}{name} ({format_number(line_counts.get(rel_path, 0))})")

    return lines


def main() -> None:
    repo_root = Path(".")
    output_path = repo_root / "files.md"

    result = subprocess.run(
        ["git", "ls-files"],
        check=True,
        capture_output=True,
        text=True,
    )
    files = sorted(line.strip() for line in result.stdout.splitlines() if line.strip())

    line_counts = {file_path: count_lines(repo_root / file_path) for file_path in files}

    extension_labels = {
        ".py": "Python",
        ".md": "Markdown",
        ".yml": "YAML",
        ".yaml": "YAML",
        ".json": "JSON",
        ".txt": "Text",
        ".sh": "Shell",
        ".ps1": "PowerShell",
        ".service": "Systemd",
    }

    extension_totals: dict[str, int] = {}
    for file_path in files:
        suffix = Path(file_path).suffix.lower()
        label = extension_labels.get(suffix)
        if label is None:
            if suffix:
                label = suffix[1:].upper()
            else:
                label = "No Extension"
        extension_totals[label] = extension_totals.get(label, 0) + line_counts[file_path]

    total_lines = sum(line_counts.values())

    tree: dict = {}
    for file_path in files:
        node = tree
        parts = file_path.split("/")
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = None

    tree_lines = ["."] + render_tree(tree, line_counts)
    body = "\n".join(tree_lines)

    content = "# File Tree\n\n"
    content += "This file is auto-generated by .github/workflows/generate-files-md.yml.\n\n"
    content += "```text\n"
    content += f"{body}\n"
    content += "```\n"
    content += "\n## Summary by Extension\n\n"

    for label in sorted(extension_totals.keys(), key=lambda item: item.casefold()):
        content += f"- {label}: {format_number(extension_totals[label])} lines\n"

    content += f"\nTotal lines: {format_number(total_lines)}\n"

    output_path.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()