on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  en_AU:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief-australia.com/einsaetze.json > Missions/en_AU.json
        curl -X GET https://www.missionchief-australia.com/alliance_event_types.json > Events/en_AU.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"

    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update en_AU
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  pt_BR:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: en_AU
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.operador193.com/einsaetze.json > Missions/pt_BR.json
        curl -X GET https://www.operador193.com/alliance_event_types.json > Events/pt_BR.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
    
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update pt_BR
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  cs_CZ:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: pt_BR
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.operacni-stredisko.cz/einsaetze.json > Missions/cs_CZ.json
        curl -X GET https://www.operacni-stredisko.cz/alliance_event_types.json > Events/cs_CZ.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"

    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update cs_CZ
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  de_DE:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: cs_CZ
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.leitstellenspiel.de/einsaetze.json > Missions/de_DE.json
        curl -X GET https://www.leitstellenspiel.de/alliance_event_types.json > Events/de_DE.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update de_DE
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  da_DK:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: de_DE
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.alarmcentral-spil.dk/einsaetze.json > Missions/da_DK.json
        curl -X GET https://www.alarmcentral-spil.dk/alliance_event_types.json > Events/da_DK.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update da_DK
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  es_ES:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: da_DK
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.centro-de-mando.es/einsaetze.json > Missions/es_ES.json
        curl -X GET https://www.centro-de-mando.es/alliance_event_types.json > Events/es_ES.json   
        
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update es_ES
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  fi_FI:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: es_ES
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.hatakeskuspeli.com/einsaetze.json > Missions/fi_FI.json
        curl -X GET https://www.hatakeskuspeli.com/alliance_event_types.json > Events/fi_FI.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update fi_FI
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  fr_FR:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: fi_FI
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.operateur112.fr/einsaetze.json > Missions/fr_FR.json
        curl -X GET https://www.operateur112.fr/alliance_event_types.json > Events/fr_FR.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update fr_FR
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  it_IT:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: fr_FR
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.operatore112.it/einsaetze.json > Missions/it_IT.json
        curl -X GET https://www.operatore112.it/alliance_event_types.json > Events/it_IT.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update it_IT
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  ja_JP:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: it_IT
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief-japan.com/einsaetze.json > Missions/ja_JP.json
        curl -X GET https://www.missionchief-japan.com/alliance_event_types.json > Events/ja_JP.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update ja_JP
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  ko_KR:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: ja_JP
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief-korea.com/einsaetze.json > Missions/ko_KR.json
        curl -X GET https://www.missionchief-korea.com/alliance_event_types.json > Events/ko_KR.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update ko_KR
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  es_MX:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: ko_KR
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.centro-de-mando.mx/einsaetze.json > Missions/es_MX.json
        curl -X GET https://www.centro-de-mando.mx/alliance_event_types.json > Events/es_MX.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update es_MX
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  nl_NL:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: es_MX
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.meldkamerspel.com/einsaetze.json > Missions/nl_NL.json
        curl -X GET https://www.meldkamerspel.com/alliance_event_types.json > Events/nl_NL.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update nl_NL
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  nb_NO:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: nl_NL
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.nodsentralspillet.com/einsaetze.json > Missions/nb_NO.json
        curl -X GET https://www.nodsentralspillet.com/alliance_event_types.json > Events/nb_NO.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update nb_NO
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  pl_PL:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: nb_NO
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.operatorratunkowy.pl/einsaetze.json > Missions/pl_PL.json
        curl -X GET https://www.operatorratunkowy.pl/alliance_event_types.json > Events/pl_PL.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update pl_PL
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  pt_PT:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: pl_PL
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.jogo-operador112.com/einsaetze.json > Missions/pt_PT.json
        curl -X GET https://www.jogo-operador112.com/alliance_event_types.json > Events/pt_PT.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update pt_PT
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  ro_RO:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: pt_PT
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.jocdispecerat112.com/einsaetze.json > Missions/ro_RO.json
        curl -X GET https://www.jocdispecerat112.com/alliance_event_types.json > Events/ro_RO.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update ro_RO
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  ru_RU:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: ro_RO
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.dispetcher112.ru/einsaetze.json > Missions/ru_RU.json
        curl -X GET https://www.dispetcher112.ru/alliance_event_types.json > Events/ru_RU.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update ru_RU
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  sv_SE:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: ru_RU
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
       git pull
       curl -X GET https://www.larmcentralen-spelet.se/einsaetze.json > Missions/sv_SE.json
       curl -X GET https://www.larmcentralen-spelet.se/alliance_event_types.json > Events/sv_SE.json
               
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update sv_SE
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  tr_TR:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: sv_SE
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.112-merkez.com/einsaetze.json > Missions/tr_TR.json
        curl -X GET https://www.112-merkez.com/alliance_event_types.json > Events/tr_TR.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update tr_TR
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  uk_UA:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: tr_TR
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.dyspetcher101-game.com/einsaetze.json > Missions/uk_UA.json
        curl -X GET https://www.dyspetcher101-game.com/alliance_event_types.json > Events/uk_UA.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update uk_UA
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  en_GB:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: uk_UA
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief.co.uk/einsaetze.json > Missions/en_GB.json
        curl -X GET https://www.missionchief.co.uk/alliance_event_types.json > Events/en_GB.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update en_GB
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  en_US:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: en_GB
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Update
      run: |
        git pull
        curl -X GET https://www.missionchief.com/einsaetze.json > Missions/en_US.json
        curl -X GET https://www.missionchief.com/alliance_event_types.json > Events/en_US.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update en_US
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}  

  sk_SK:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: en_US
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: update
      run: |
        git pull
        curl -X GET https://www.dispecerske-centrum.com/einsaetze.json > Missions/sk_SK.json
        curl -X GET https://www.dispecerske-centrum.com/alliance_event_types.json > Events/sk_SK.json
                
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code & PUSH
      uses: creyD/prettier_action@v4.0
      with:
        prettier_options: --write **/*.{js,md,json}
        commit_message: Update sk_SK
      env:
        GITHUB_TOKEN: ${{ secrets.MISSIONBOT }}    
